apiVersion: v1
kind: Service                                      # Pods ko network access deta hai
metadata:
  name: java-login-app-service
  namespace: default 

spec:
  selector:
    app: java-login-app  #Deployment labels se EXACTLY match karo!
  ports:
  - protocol: TCP
    port: 80                                            # Service ka port
    targetPort: 8080                                    # Pod ke andar ka port
  type: NodePort                                        # VM ke bahar se accessible
                                                        # K8s automatically 30000-32767 range mein port dega
  
